import pandas as Shaistu
Rashid = Shaistu.read_csv("dataset.csv")
print("\n----- FIRST 5 ROWS -----")
print(Rashid.head())
print("\n-----  TOTAL CONTENT COUNT -----")
print(len(Rashid))
print("\n ----- TOTAL VIEWS -----")
print(Rashid["Views"].sum())
top_row = Rashid.sort_values("Views",ascending=False)
print(top_row[["Title","Scholar","Views"]])
print("\n----- SCHOLAR WISE TOTAL VIEWS -----")
scholar_views= Rashid.groupby("Scholar")["Views"].sum()
print(scholar_views)
top_scholar=scholar_views.idxmax()
print("\n MOST POPULAR SCHOLAR:", top_scholar)
print("\n Top 3 scholars")
print(scholar_views.sort_values(ascending=False).head(3))
print("\n------ CATEGORY WISE TOTAL VIEWS ------")
category_views = Rashid.groupby("Category")["Views"].sum()
print(category_views)
top_category = category_views.idxmax()
print("\nMost Popular Category:", top_category)
print("\n------ TOP 3 CATEGORIES ------")
print(category_views.sort_values(ascending=False).head(3))
Rashid["Uploaded_Date"] = Shaistu.to_datetime(Rashid["Uploaded_Date"])
Rashid["Month"] = Rashid["Uploaded_Date"].dt.month
print("\n------ MONTH WISE TOTAL VIEWS ------")
month_views = Rashid.groupby("Month")["Views"].sum()
print(month_views)
top_month = month_views.idxmax()
print("\nMost Trending Month:", top_month)

